###This code will not work in repl.it as there is no access to the colorgram package here.###
##We talk about this in the video tutorials##
import colorgram
import turtle as t
import random as r

rgb_colors = []
colors = colorgram.extract('Daily Projects\Day 18 - Hirst Painting\\aqua_fanart.png', 200)
for color in colors:
    rgb_colors.append(color.rgb)

def get_color():
    """Get a color from the list of colors generated by the colorgram.py earlier

    Returns:
        tuple: red green and blue values to be used by the Turtle
    """
    
    red = r.choice(rgb_colors)[0]
    green = r.choice(rgb_colors)[1]
    blue = r.choice(rgb_colors)[2]
    color_code = (red,green,blue)

    return color_code

def horiz_dots():
    """Draw dots horizontally across the screen
    """
    for i in range(0,13):
        timmy.pencolor(get_color())
        timmy.pendown()
        timmy.forward(1)
        timmy.penup()
        timmy.forward(99)

def go_down():
    """Go down while offscreen
    """
    if timmy.xcor() > 0:
        timmy.rt(90)
        timmy.forward(100)
        timmy.rt(90)
        timmy.forward(100)
    if timmy.xcor() < 0: 
        timmy.lt(90)
        timmy.forward(100)
        timmy.lt(90)
        timmy.forward(100)

def set_screen():
    """Set the initial screen size and color

    Returns:
        Screen: the Screen for the Turtle to darw on
    """
    screen = t.Screen()
    t.screensize(640,640,"grey10")
    return screen

def set_turtle():
    """ Instantiates the Turtle, sets the Turtles color, and positions it to start drawing from the top left

    Returns:
        Turtle: The Turtle we are going to be using to draw
    """
    t.colormode(255)
    timmy = t.Turtle()
    timmy.shape('triangle')
    timmy.color((0,255,255))
    timmy.pencolor(get_color())
    timmy.pensize(50)
    timmy.penup()
    timmy.setx(-600)
    timmy.sety(500)
    return timmy


screen = set_screen()
timmy = set_turtle()

for i in range(0,13):
    horiz_dots()
    go_down()
    horiz_dots()
    go_down()

screen.exitonclick()